services:

  api:
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    container_name: trivia-api
    volumes:
    # map source code for live updates with nodemon
      - ./app/backend:/app
    # map shared ws-api
      - ./shared/ws-api.js:/app/ws-api.js
    # anonymous volume to protect containers node_modules (prevents host node_modules from overwriting)
      - /app/node_modules 
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    # use nodemon for live updates
    command: nodemon server.js

  frontend:
    image: nginx:alpine
    container_name: trivia-frontend
    volumes:
      - ./app/frontend:/usr/share/nginx/html
      - ./shared/ws-api.js:/usr/share/nginx/html/public/js/ws-api.js
    expose:
      - "80"

  db:
    image: mysql:8.0
    container_name: trivia-db
    restart: always
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3307"

  apacheshib:
    image: dockerhub.csc.ncsu.edu/ignacioxd/apacheshib-proxy
    container_name: shib-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - frontend
    environment:
      - SERVER_NAME=localhost
      - LOGIN_PATH=/teacher
      - BACKEND_HOST=api
      - BACKEND_PORT=8080
      - BACKEND_PATH=/api
      - BACKEND_PROTOCOL=http
      - FRONTEND_HOST=frontend
      - FRONTEND_PORT=80
      - FRONTEND_PROTOCOL=http

volumes:
  mysql-data: