USE trivia;

CREATE TABLE IF NOT EXISTS users (
    userID INT AUTO_INCREMENT PRIMARY KEY,
    unityID VARCHAR(255) NOT NULL,
    note VARCHAR(255) NOT NULL,
    questionPriv BOOLEAN NOT NULL DEFAULT FALSE,
    userPriv BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS questions (
    questionID INT AUTO_INCREMENT PRIMARY KEY,
    question VARCHAR(255) NOT NULL,
    corrAnswer VARCHAR(255) NOT NULL,
    incorrONE VARCHAR(255) NOT NULL,
    incorrTWO VARCHAR(255) NOT NULL,
    incorrTHREE VARCHAR(255) NOT NULL,
    category INT NOT NULL,
    -- creatorID INT REFERENCES users(userID), -- could be useful?
    isAI BOOLEAN NOT NULL DEFAULT FALSE
);

